import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { migrate,importSeed } from "../migrate.ts";
import { makePool } from "../db.ts";
import { Repository } from "../repository.ts";
import { makeApp } from "../app.ts";
import { totpAt } from "../auth.ts";

test("Database-backed editor/publication/auth integration",{skip:process.env.PROZHITO_INTEGRATION!=="1"},async()=>{
  assert.equal(process.env.PROZHITO_LOCAL_TEST,"1");
  assert.equal(process.env.PGHOST,"127.0.0.1");
  assert.equal(process.env.PGPORT,"55432");
  await migrate();await migrate();
  const seed=JSON.parse(readFileSync(new URL("../../.work/prozhito/seed/seed.json",import.meta.url),"utf8"));
  const password="synthetic-integration-password-only";
  await importSeed(seed,password);
  await assert.rejects(importSeed(seed,password),/empty content/);
  process.env.PGUSER="prozhito_app";
  const pool=makePool();const repo=new Repository(pool);
  let clock=new Date("2026-08-31T12:00:00Z");
  const secret="GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ";
  const app=await makeApp({repo,adminOrigin:"http://localhost:5174",totpSecret:secret,rateSecret:"test-rate-secret-is-synthetic-and-private-to-this-test",local:true,now:()=>clock});
  const headers={host:"localhost:5174",origin:"http://localhost:5174"};
  try {
    await assert.rejects(pool.query("CREATE TABLE prozhito.forbidden(id integer)"),/permission denied/);
    await assert.rejects(pool.query("UPDATE prozhito.revisions SET document=document"),/permission denied/);
    await assert.rejects(pool.query("UPDATE prozhito.editors SET enabled=false"),/permission denied/);
    const anonymous=await app.inject({url:"/api/v1/content"});
    assert.equal(anonymous.statusCode,200);assert.equal(anonymous.json().items.length,22);
    assert.equal(anonymous.headers["set-cookie"],undefined);
    assert.equal((await app.inject({url:"/api/admin/content",headers})).statusCode,401);
    assert.equal((await app.inject({url:"/api/admin/content"})).statusCode,403);
    const login=await app.inject({method:"POST",url:"/api/admin/login",headers,payload:{login:"editor",password,code:totpAt(secret,Math.floor(clock.getTime()/30000))}});
    assert.equal(login.statusCode,200,login.body);
    const auth={...headers,cookie:String(login.headers["set-cookie"]).split(";")[0],"x-csrf-token":login.json().csrfToken};
    const original=anonymous.json();
    const draft=(await app.inject({url:"/api/admin/sections/L01-S01",headers:auth})).json();
    assert.deepEqual(Object.keys(draft).sort(),["baseRevisionId","document","version"]);
    const document={...draft.document,title:draft.document.title+" (тест)"};
    const payload={version:draft.version,baseRevisionId:draft.baseRevisionId,document};
    const broken=structuredClone(payload);broken.document.visuals.story.src="/media/missing.jpg";
    assert.equal((await app.inject({method:"PUT",url:"/api/admin/sections/L01-S01",headers:auth,payload:broken})).statusCode,400);
    const brokenCrop=structuredClone(payload);delete brokenCrop.document.editorial.story.focal;
    assert.equal((await app.inject({method:"PUT",url:"/api/admin/sections/L01-S01",headers:auth,payload:brokenCrop})).statusCode,400);
    const rejected=await app.inject({method:"PUT",url:"/api/admin/sections/L01-S01",headers:{...auth,"x-csrf-token":"invalid"},payload});
    assert.equal(rejected.statusCode,403);
    const saved=await app.inject({method:"PUT",url:"/api/admin/sections/L01-S01",headers:auth,payload});
    assert.equal(saved.statusCode,200,saved.body);
    assert.equal((await app.inject({url:"/api/v1/content"})).json().items[0].document.title,draft.document.title);
    assert.equal((await app.inject({method:"PUT",url:"/api/admin/sections/L01-S01",headers:auth,payload})).statusCode,409);
    const published=await app.inject({method:"POST",url:"/api/admin/sections/L01-S01/publish",headers:auth,payload:{version:saved.json().version,reason:"Synthetic integration test"}});
    assert.equal(published.statusCode,200,published.body);
    const updated=(await app.inject({url:"/api/v1/content"})).json();
    assert.equal(updated.items[0].document.title,document.title);
    const rolled=await app.inject({method:"POST",url:"/api/admin/rollback",headers:auth,payload:{target:original.id,expectedCurrent:updated.id,reason:"Restore original synthetic test publication"}});
    assert.equal(rolled.statusCode,200,rolled.body);
    assert.deepEqual((await app.inject({url:"/api/v1/content"})).json().items,original.items);
    const currentDraft=(await app.inject({url:"/api/admin/sections/L01-S01",headers:auth})).json();
    const futureDraft=(await app.inject({method:"PUT",url:"/api/admin/sections/L01-S01",headers:auth,payload:currentDraft})).json();
    assert.equal((await app.inject({method:"POST",url:"/api/admin/sections/L01-S01/discard",headers:auth,payload:{version:futureDraft.version+1}})).statusCode,409);
    assert.equal((await app.inject({method:"POST",url:"/api/admin/sections/L01-S01/discard",headers:auth,payload:{version:futureDraft.version}})).statusCode,200);
    assert.equal((await app.inject({method:"POST",url:"/api/admin/login",headers,payload:{login:"editor",password,code:totpAt(secret,Math.floor(clock.getTime()/30000))}})).statusCode,401);
    let nightReadinessCalls=0;repo.ready=async()=>{nightReadinessCalls++;throw new Error("Database is stopped");};
    clock=new Date("2026-08-31T21:00:00Z");
    assert.equal((await app.inject({url:"/api/v1/content"})).statusCode,503);
    assert.equal((await app.inject({url:"/api/admin/session",headers:auth})).statusCode,503);
    const status=(await app.inject({url:"/api/status"})).json();
    assert.equal(status.mode,"scheduled_maintenance");assert.equal(status.nextOpenAt,"2026-09-01T05:00:00.000Z");
    assert.equal(nightReadinessCalls,0);
  } finally {await app.close();await pool.end();}
});
